var namespace_h_o_s_t___admin_1_1_models_1_1_view_model =
[
    [ "SharePointSOAPRequestViewModel", "class_h_o_s_t___admin_1_1_models_1_1_view_model_1_1_share_point_s_o_a_p_request_view_model.html", "class_h_o_s_t___admin_1_1_models_1_1_view_model_1_1_share_point_s_o_a_p_request_view_model" ],
    [ "SharePointSOAPResponseViewModel", "class_h_o_s_t___admin_1_1_models_1_1_view_model_1_1_share_point_s_o_a_p_response_view_model.html", "class_h_o_s_t___admin_1_1_models_1_1_view_model_1_1_share_point_s_o_a_p_response_view_model" ]
];