package org.habitatomaha.HOST.Model;

import java.io.Serializable;

import org.simpleframework.xml.Element;

/**
 * This class represents all the meta data within a form.
 */
public class Meta implements Serializable{

	private static final long serialVersionUID = 3503635432336091621L;
	
	/**
	 * This element represents who filled out the form. 
	 */
	@Element (name="filledbyfieldname", required=false)
    public String filledByFieldName;
    /**
     * This element represents the data type of the filledByFieldName attribute.
     */
    @Element (name="filledbyfieldtype")
    public String filledByFieldType;
   
    /**
     * This element represents the date when the form was filled out.
     */
    @Element (name="filleddatefieldname", required=false)
    public String filledDateFieldName;
    
    /**
     * This element represents the data of the filledDateFieldName attribute. 
     */
    @Element (name="filleddatefieldtype")
    public String filledDateFieldType;
    
    public String filledDate;
    public String filledBy;
	
	
	/**
	 * This element is an identifier for the particular template being used.
	 * Generated by the admin tool.
	 */
	@Element (name="template_id")
	public long template_id;
	
	/**
	 * This element is an identifier for the particular form being used.
	 * Generated within the mobile app.
	 */
	public long form_id;
	
	//TODO name miss match
	@Element (name="formgroup", required=false)
	public String group;
	
	/**
	 * This element represents the name of the form.
	 * Generated by the admin tool
	 */
	@Element (name="name")
	public String name;
	
	/**
	 * This element provides a description for the form.
	 * Generated by the admin tool.
	 */
	@Element (name="description", required=false)
	public String description;
	
	//TODO -- remove these from admin?
	/**
	 * This element represents the username used to log into the SharePoint site.
	 * Generated from the user settings (SharedPreferences).
	 */
	@Element (name="user", required=false)
	public String user;
	
	//TODO -- remove these from admin?
	/**
	 * This element represents the password used to log into the SharePoint site.
	 * Generated from user settings (SharedPreferences).
	 */
	@Element (name="pass", required=false)
	public String pass;
	
	/** 
	 * This element represents the URL that the form's SharePoint list is being housed on.
	 * Generated from user settings (SharedPreferences).
	 */
	@Element (name="url")
	public String url;
	/**
	 * This element represents the port number used when accessing the form's SharePoint list.
	 * Generated form user settings (SharedPreferences).
	 */
	@Element (name="port")
	public String port;
	
	
	//TODO - this really shouldnt ever be blank
	/** 
	 * This element represents the list name of the particular SharePoint site of the form.
	 * Generated by the admin tool.
	 */
	@Element (name="listname", required=false)
	public String listname;
	
	//TODO - this really shouldnt ever be blank
	/**
	 * This element designates which field should be used as the "key field", i.e. what shows up to identify the form in the main menu screen.
	 * Generated by the admin tool.
	 */
	@Element (name="keyfield", required=false)
	public String keyfield;
	
	/**
	 * This element designates whether this form should be uploaded as soon as the devices recognizes it is connected to wireless.
	 * Generated by the admin tool.
	 */
	@Element (name="autoupload")
	public String autoUpload;
	
	/**
	 * This element designates the date that the form was created.
	 * Generated by the admin tool.
	 */
	@Element (name="datecreated")
	public String dateCreated;
	
	//TODO - remove/update
	public long getFormID(){
		return template_id;
	}
	
	/**
	 * This method returns the name of the form.
	 * @return name - form name
	 */
	public String getFormName(){
		return name;
	}
	
}
